### ISSUE TITLE
Qns about experiment result

### ISSUE THREAD

**Issue by Yuxin916** [LijunSun90/pursuitFSC2#2]
Hi! 
I noticed that you have an experiment log file: /data/stp_rl_pursuer_6_6_4_1_.txt. 

This single target pursuit problem set up. world_size = 6, n_pursuers = 4 and n_evaders = 1. May i ask 

1. And how many epoch you recommended for training? the default 1e5?
2. What is the fov_scope under this scenario? 
3. What is the difference between stp_6_6_4_1_.txt and sop_40_40_4_1_.txt other than the size of map become bigger?

Thank you for your help!

**Comment by LijunSun90** [comment]
> Hi! I noticed that you have an experiment log file: /data/stp_rl_pursuer_6_6_4_1_.txt.
> 
> This single target pursuit problem set up. world_size = 6, n_pursuers = 4 and n_evaders = 1. May i ask
> 
> 1. And how many epoch you recommended for training? the default 1e5?
> 2. What is the fov_scope under this scenario?
> 3. What is the difference between stp_6_6_4_1_.txt and sop_40_40_4_1_.txt other than the size of map become bigger?
> 
> Thank you for your help!

Hi, 

0. First, The stp_rl_pursuer_6_6_4_1_.txt is an outdated result that is trained with A2C using a different reward function. This result is abandoned because we found that the reward function used is not suitable for the training with more than one evaders. Hence, we change that reward function to the current one, which performs good for the cases of multiple evaders. 

1. As for the training epochs, for the simplest case of 4 pursuers vs. 1 static evader, 1000 training epochs are sufficient to observe the convergence. But for complex cases, such as with more evaders, stronger evaders, and in bigger environments, more epochs are needed. For example, for multiple static or random-walking evaders, 5000 epochs are sufficient for A2C.
2. The for_scope is always 11, the default value.
3. sop_40_40_4_1_.txt is the newest result with the current reward function.

Best regards!

**Comment by Yuxin916** [comment]
Thank you for your answer! :) :+1:
