### ISSUE TITLE
The train_sos_apexdqn.py file is always in the pendinc state. Procedure

### ISSUE THREAD

**Issue by LZL-boy** [LijunSun90/pursuitFSC2#8]
It's always been this way
== Status ==
Current time: 2024-05-27 21:24:51 (running for 00:00:10.13)
Memory usage on this node: 11.9/15.7 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/5 CPUs, 0/4 GPUs, 0.0/2.56 GiB heap, 0.0/1.28 GiB objects
Result logdir: C:\Users\Jarvis\Desktop\pursuitFSC2-main\multi_target_self_organizing_search\results\sos_apexdqn\ADQN
Number of trials: 1/1 (1 PENDING)
+--------------------------+----------+-------+
| Trial name               | status   | loc   |
|--------------------------+----------+-------|
| APEX_pursuit_79642_00000 | PENDING  |       |
+--------------------------+----------+-------+

**Comment by LijunSun90** [comment]
The ApexDQN algorithm is based on the Ray library. If the status is always PENDING, it means the training does not run at all. It is recommended to run on a workstation or server, rather than a PC or laptop. To fit your computation resources, parameters in line 57-59 of train_sos_apexdqn.py need to be adjusted accordingly.

**Comment by LijunSun90** [comment]
The ApexDQN algorithm is based on the Ray library. If the status is always PENDING, it means the training does not run at all. It is recommended to run on a workstation or server, rather than a PC or laptop. To fit your computation resources, parameters in line 57-59 of train_sos_apexdqn.py need to be adjusted accordingly.
